import {
  Award,
  BookOpen,
  Briefcase,
  Building2,
  Crown,
  Factory,
  FlaskConical,
  GraduationCap,
  HeartPulse,
  Hotel,
  Landmark,
  Leaf,
  Monitor,
  Palette,
  Pill,
  Scale,
  Shield,
  ShieldCheck,
  TrainFront,
  Wallet,
  Wrench,
  Wheat,
  Fuel,
  Castle,
  Mountain,
  Church,
  TreePalm,
  Waves,
  MapPin,
  Trees,
} from "lucide-react";

export const qualificationIconMap = {
  book: BookOpen,
  graduationCap: GraduationCap,
  wrench: Wrench,
  award: Award,
  briefcase: Briefcase,
  heartPulse: HeartPulse,
  scale: Scale,
  wallet: Wallet,
  flaskConical: FlaskConical,
  palette: Palette,
  monitor: Monitor,
  leaf: Leaf,
  pill: Pill,
  building2: Building2,
  hotel: Hotel,
};

export const categoryIconMap = {
  crown: Crown,
  train: TrainFront,
  landmark: Landmark,
  ashoka: ShieldCheck,
  building: Building2,
  shield: Shield,
  factory: Factory,
};

export const organizationIconMap = {
  building: Building2,
  landmark: Landmark,
  train: TrainFront,
  shield: ShieldCheck,
  factory: Factory,
  education: GraduationCap,
  medical: HeartPulse,
  judiciary: Scale,
  agriculture: Wheat,
  energy: Fuel,
} as const;

export const stateIconMap = {
  castle: Castle,
  mountain: Mountain,
  temple: Church,
  nature: TreePalm,
  coast: Waves,
  heritage: Landmark,
  location: MapPin,
  trees: Trees,
} as const;
